* About
kdeconnect.el is a package that provides helper functions for the excellent [[https://community.kde.org/KDEConnect][KDE Connect]] package available for computers and Android devices.
Now you can send files across devices or make your phone ring when you can't find the darn thing, all without ever leaving Emacs!

* Setup
Install KDE Connect on your Android device(s) using [[https://f-droid.org/repository/browse/?fdfilter=kde+connect&fdid=org.kde.kdeconnect_tp][F-Droid]] or the [[https://play.google.com/store/apps/details?id=org.kde.kdeconnect_tp][Google Play Store]].
Also install it on any computers you want.
As of this writing, KDE Connect requires Linux, and is probably in your distro's repos already.
It does /not/ require KDE.
Pair your devices from these applications.

Install the Emacs package and add =(require 'kdeconnect)= to your =init.el= file.
After installation, you can set a default device by adding
#+BEGIN_SRC emacs-lisp
(setq kdeconnect-device "<device ID>")
#+END_SRC
to your =init.el= file.
Device IDs for available devices can be found by calling =M-x kdeconnect-list-devices=.
If you do not want a default device, you can set the active device for your session with =M-x kdeconnect-select-device.=
This function works even if you already set a default device.

* Usage
After selecting an active device, the following functions are available.
| Function                 | Description                                                                                                                                               |
|--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------|
| kdeconnect-get-active-device | Display the active device                                                                                                                                 |
| kdeconnect-list-devices  | Display all available devices                                                                                                                             |
| kdeconnect-ping          | Send a notification to the active device                                                                                                                  |
| kdeconnect-ping-msg      | Send a notification with a custom message to the active device                                                                                            |
| kdeconnect-ring          | Make the active device ring (useful for finding it)                                                                                                       |
| kdeconnect-select-device | Select the active device from all available ones (you should call =kdeconnect-list-devices= first if you don't already know the ID of the desired device) |
| kdeconnect-send-file     | Send the selected file to the active device                                                                                                               |

* Troubleshooting
If you're not seeing any response from your desired device, make sure there is an active connection.
You can use =M-x kdeconnect-list-devices= or open up KDE Connect to make sure.
